### ISSUE TITLE
"RuntimeError: No input file to read network" when visualizing a network

### ISSUE THREAD

**Issue by jukkahuhtamaki** [simonlindgren/graphmonster#1]
I was trying to visualize a monster graph. However, I run into the following error:

```
- graphcrunch function
----- Creating weighted graph from edgelist
----- Removing edges by threshold
----- Deleting unconnected components
----- Renaming nodes

- infomap_clu function
----- Building Infomap network
----- Finding communities
Traceback (most recent call last):
  File "gm.py", line 257, in <module>
    main()
  File "gm.py", line 56, in main
    infomap_clu(G)
  File "gm.py", line 122, in infomap_clu
    infomapX.run();
  File "/Users/foobar/graphmonster/env/lib/python3.8/site-packages/infomap.py", line 4234, in run
    return super().run(args)
  File "/Users/foobar/env/lib/python3.8/site-packages/infomap.py", line 3184, in run
    return _infomap.InfomapWrapper_run(self, *args)
RuntimeError: No input file to read network
```

**Comment by simonlindgren** [comment]
This error message comes from the infomap library, which seems to lack an input file to read. Can you share your edgelist file, or part of it, and I can try to troubleshoot?

**Comment by jukkahuhtamaki** [comment]
Awesome, thank you @simonlindgren! I am uploading an input file now, you will receive a link in your email.

**Comment by simonlindgren** [comment]
First, I noted that your file lines read:

```
1 123 456
```

With line number; source; target. The right format is simply source; target:

```
123 456
```

This may or may not be the cause of your error. I will get back to you when I have finished the run of your file.

**Comment by simonlindgren** [comment]
The above was the error. After removing the line numbers, the graph was created correctly.

**Comment by simonlindgren** [comment]
If you need it, here is code to create a new edgelist file without the index:

```
import pandas as pd

df = pd.read_csv("edgelist.txt", sep=" ", names = ["a","b","c"])
df = df[['b', 'c']]
df.to_csv("new_edgelist.txt", index = False, header = False, sep = " ")
```

**Comment by jukkahuhtamaki** [comment]
Thank you @simonlindgren and apologies for the trouble. Will now move forward testing the tool.
